require 'date'
require 'fileutils'
require 'pathname'

def body(document, filename)
  html = ""

  html += "<header><div class='pad'>"
  
  #----------------
  # bread crumbs
  path = Pathname.new(filename)
  base = Pathname.new("./public")
  path = path.relative_path_from(base).sub_ext(".html")
  bread = "<a href='/'>monman53.github.io</a> / "
  path.descend do |v|
      if v.extname != ".html"
          bread += "<a href='/" + v.to_s + "/'>" + v.basename.to_s + "</a> / "
      else
          if v.basename.to_s != "index.html"
              bread += "<a href='/" + v.to_s + "'>" + v.basename.to_s + "</a>"
          end
      end
  end
  html += "<p class='bread'>" + bread + "</p>"
  html += "<p style='font-size: small;'>Last Modified : #{File::Stat.new(filename).mtime}</p>"
  #----------------

  html += "</div></header>"
  html += "<article><div class='pad'>"

  #----------------
  # title
  html += "<h1>#{document.doctitle}</h1>"
  #----------------

  #================
  # Main contents
  #================
  html += document.content

  #----------------
  # footnotes
  if document.footnotes?
      html += "<hr>"
      html += "<h4>脚注</h4>"
      document.footnotes.each{|footnote|
          html += "<p id='_footnote_#{footnote[:index].to_s}'><small>#{footnote[:index].to_s}. #{footnote[:text]}</small></p>"
      }
  end
  #----------------

  html += "</div></article>"

  #----------------
  # footer
  html += "<footer><div class='pad'>"
  #html += "<p>Created : #{File::Stat.new(filename).ctime}</p>"
  html += "<p>Last Modified : #{File::Stat.new(filename).mtime}</p>"
  html += "<p><a href='/'>monman53.github.io</a></p>"
  html += "<p>This page is generated by <a href='https://github.com/monman53/monsta'>monsta</a>.</p>"
  html += "<p><a rel='license' href='http://creativecommons.org/licenses/by/4.0/'><img alt='Creative Commons License' style='border-width:0' src='/images/cc-by.png' height='30px'/></a><br>"
  html += "This work is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License</a>.</p>"
  html += "</div></footer>"
  #----------------

  html
end
