require 'asciidoctor'
require 'asciidoctor/extensions'
require 'date'

document = Asciidoctor.load_file ARGV[0]


#----------------
# header
#----------------
puts "<!doctype html>"
puts "<meta charset='UTF-8'>"
puts "<meta name='viewport' content='width=device-width, initial-scale=1'>"
puts "<link rel='stylesheet' href='/css/main.css'>"
puts "<title>" + document.doctitle + " : monman53" + "</title>"

# css, script
puts "<link rel='stylesheet' href='/css/github.css'>"
puts "<script src='/js/highlight.pack.js'></script>"
puts "<script>hljs.initHighlightingOnLoad();</script>"

# title
puts "<h1>" + document.doctitle + "</h1>"
puts "<p><a href='/'>monman53.github.io</a></p>"
puts "<hr>"


#----------------
# content
#----------------

# main
puts document.content
#puts document.footnotes[0][:text] if document.footnotes?

# footnotes
if document.footnotes?
    puts "<hr>"
    puts "<h4>脚注</h4>"
    document.footnotes.each{|footnote|
        puts "<p><small>" + footnote[:index].to_s + ". " + footnote[:text] + "</small></p>"
    }
end


#----------------
# footer
#----------------
puts "<hr>"
puts "<p><tt>last update : " + DateTime.now.strftime("%Y-%m-%d %H:%M:%S (%Z)") + "</tt></p>"
puts "<p><a href='/'>monman53.github.io</a></p>"
puts "<p>this page is generated by <a href='https://github.com/monman53/monsta'>monsta</a></p>"
puts "<script src='/js/LaTeXMathML.js'></script>"
puts "<script src='/js/ASCIIMathML.js'></script>"
