#!/bin/bash

# footer
echo "<hr>"
echo "<p>generated by monman static site generator</p>"

# scripts
echo "<script src='/js/LaTeXMathML.js'></script>"
echo "<script src='/js/ASCIIMathML.js'></script>"
