#!/bin/bash

# filenames
adoc=$1
html=$2

# source file timestamp
epoch=`stat -c %Y $adoc`
timestamp=`date -u -d \@${epoch} +'%F %T'`

# get title
title=`head -n 1 $adoc`


#----------------
# header
#----------------

echo "<!doctype html>"
echo "<meta name='viewport' content='width=device-width, initial-scale=1'>"
echo "<meta charset='utf-8'>"
echo "<link rel='stylesheet' href='/css/main.css'>"
# echo "<link rel='stylesheet' href='/css/asciidoc.css'>"

# title
echo "<title>$title</title>"
echo "<h1>$title</h1>"
echo "<a href='/'>[Top]</a>"
# echo "<a href='https://powerman.name/doc/asciidoc'>[asciidoc cheat sheet]</a>"
echo "<hr>"
echo "<h3>Table of Contents</h3>"
echo "<div id='toc'></div>"
echo "<div id='content'>"


#----------------
# contents
#----------------

cat $html


#----------------
# footer
#----------------

echo "</div>"
echo "<h2>脚注</h2>"
echo "<div id='footnotes'></div>"
echo "<hr>"
echo "<p>last update ${timestamp} (UTC)</p>"
echo "<p>this page is generated by <a href='https://github.com/monman53/monsta'>monsta</a></p>"

# scripts
echo "<script src='/js/asciidoc.js'></script>"
echo "<script>asciidoc.install(1);</script>"
echo "<script src='/js/LaTeXMathML.js'></script>"
echo "<script src='/js/ASCIIMathML.js'></script>"
