#!/bin/bash

#----------------
# header
#----------------

echo "<!doctype html>"
echo "<meta name='viewport' content='width=device-width, initial-scale=1'>"
echo "<meta charset='utf-8'>"
echo "<link rel='stylesheet' href='/css/main.css'>"

# scripts
# echo "<script src='/js/asciidoc.js'></script>"
# echo "<script src='/js/toc.js'></script>"

# title
title=$(head -n 1 $1)
echo "<title>$title</title>"
echo "<h1>$title</h1>"
echo "<a href='/'>Top</a>"
echo "<hr>"


#----------------
# contents
#----------------

cat $2


#----------------
# footer
#----------------

echo "<hr>"
echo "<p>generated by <a href='https://github.com/monman53/monsta'>monsta</a></p>"

# scripts
echo "<script src='/js/LaTeXMathML.js'></script>"
echo "<script src='/js/ASCIIMathML.js'></script>"
