#!/usr/bin/perl

my $adoc = $ARGV[0];
my $html = $ARGV[1];

open(FH, "< $adoc");
my $title = <FH>;
close(FH);


#----------------
# header
#----------------

print "<!doctype html>";
print "<meta name='viewport' content='width=device-width, initial-scale=1'>";
print "<meta charset='utf-8'>";
print "<link rel='stylesheet' href='/css/main.css'>";

# title
print "<title>$title</title>";
print "<h1>$title</h1>";
print "<a href='/'>[Top]</a>";
print "<a href='https://powerman.name/doc/asciidoc'>[asciidoc cheat sheet]</a>";
print "<hr>";


#----------------
# contents
#----------------

# open(FH, "< $html");
# while(<FH>) {
#     print;
# }
# close(FH);
system("cat $html");


#----------------
# footer
#----------------

print "<hr>";
print "<p>generated by <a href='https://github.com/monman53/monsta'>monsta</a></p>";

# scripts
print "<script src='/js/LaTeXMathML.js'></script>";
print "<script src='/js/ASCIIMathML.js'></script>";

# my @list = split(/\//, $ARGV[0]);
#
# foreach my $dir (@list) {
#     print "$dir\n";
# }
